import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { copyFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const serviceAccountPath = resolve(__dirname, "service-account.json");
const envPath = resolve(__dirname, ".env");

const installCommand = process.platform === "win32" ? "npm.cmd install" : "npm install";
const registerCommand = "claude mcp add --transport stdio shared-context -- node index.js";
const registerArgs = ["mcp", "add", "--transport", "stdio", "shared-context", "--", "node", "index.js"];

function claudeBinary() {
  return process.platform === "win32" ? "claude.cmd" : "claude";
}

async function ask(cli, question) {
  return (await cli.question(question)).trim();
}

async function confirm(cli, question, defaultYes = true) {
  const hint = defaultYes ? "[Y/n]" : "[y/N]";
  const answer = await ask(cli, `${question} ${hint} `);
  if (answer === "") return defaultYes;
  return /^y(es)?$/i.test(answer);
}

async function setupDrive(cli) {
  console.log("");
  console.log("Google Drive sync (recommended, shared across the whole team)");
  console.log("---------------------------------------------------------------");

  if (existsSync(serviceAccountPath)) {
    console.log(`Found an existing key at ${serviceAccountPath} — leaving it in place.`);
  } else {
    console.log("This needs a shared Google Cloud service-account key (one JSON file,");
    console.log("reused by everyone on the team — no per-person browser login required).");
    console.log("");
    console.log("If your team doesn't have one yet, create it once:");
    console.log("  1. https://console.cloud.google.com/iam-admin/serviceaccounts -> Create service account");
    console.log("  2. Grant it no project roles (Drive access comes from sharing a folder with it)");
    console.log("  3. Keys tab -> Add key -> JSON, download it");
    console.log("  4. Enable the Drive API for the project: https://console.cloud.google.com/apis/library/drive.googleapis.com");
    console.log("  5. In Google Drive, share your team's shared-context folder with the");
    console.log("     service account's email (client_email in the JSON) as an Editor");
    console.log("");
    const keyPath = await ask(cli, "Path to the service-account JSON key (blank to skip Drive setup): ");
    if (!keyPath) {
      console.log("Skipped. Falling back to local-file sync — rerun `npm run setup` anytime to add Drive.");
      return;
    }
    const resolvedKeyPath = resolve(keyPath.replace(/^~(?=$|\/)/, process.env.HOME || ""));
    if (!existsSync(resolvedKeyPath)) {
      console.log(`Could not find ${resolvedKeyPath} — skipping Drive setup.`);
      return;
    }
    await copyFile(resolvedKeyPath, serviceAccountPath);
    console.log(`Copied key to ${serviceAccountPath} (kept out of git via .gitignore).`);
  }

  const folderId = await ask(
    cli,
    "Google Drive folder ID to sync into (blank = each teammate gets their own file in the service account's Drive root): "
  );

  const lines = [
    "# Generated by `npm run setup`. Not committed — see .gitignore.",
    `GOOGLE_APPLICATION_CREDENTIALS=${serviceAccountPath}`
  ];
  if (folderId) lines.push(`GOOGLE_DRIVE_FOLDER_ID=${folderId}`);
  await writeFile(envPath, `${lines.join("\n")}\n`, "utf8");
  console.log(`Wrote ${envPath}`);
  console.log("Drive sync is now the default backend (set SHARED_CONTEXT_BACKEND=local to opt out).");
}

try {
  execSync(installCommand, { stdio: "inherit" });

  const cli = createInterface({ input, output });
  try {
    if (await confirm(cli, "\nSet up Google Drive sync now?")) {
      await setupDrive(cli);
    } else {
      console.log("Skipped. Using local-file sync — rerun `npm run setup` anytime to add Drive.");
    }

    console.log("");
    console.log(registerCommand);
    console.log("");

    if (await confirm(cli, "Register this MCP server in Claude Code now?")) {
      execSync(`${claudeBinary()} ${registerArgs.join(" ")}`, { stdio: "inherit" });
      console.log("");
      console.log("Claude Code registration complete.");
    } else {
      console.log("Skipped automatic registration. You can run the command above later.");
    }
  } finally {
    cli.close();
  }
} catch (error) {
  process.exitCode = 1;
  throw error;
}
